defaults:
    - local: hpack-common.yaml

name: warp-tls-simple
version: 0.1.1.0
license: MIT
copyright: 2025 Juspay
maintainer: srid@srid.ca
author: Sridhar Ratnakumar
homepage: https://github.com/srid/warp-tls-simple
category: Web
synopsis: Simple TLS configuration for Warp
description: Simplified TLS setup and certificate generation for Warp servers

dependencies:
    - directory
    - filepath
    - which
    - optparse-applicative
    - process
    - wai
    - warp
    - warp-tls

library:
    source-dirs: src
